### ISSUE TITLE
Connectivity question

### ISSUE THREAD

**Issue by pascalandy** [alexellis/mine-with-docker#2]
Here I'm mining on few servers. I see two different issues.

## Civo

`docker ps` - It runs

![screen shot 2018-01-03 at 10 38 03 am](https://user-images.githubusercontent.com/6694151/34527044-3d043484-f072-11e7-9237-d03c783902b2.jpg)

`docker service logs miner` - I see these issues in the logs

![screen shot 2018-01-03 at 10 36 52 am](https://user-images.githubusercontent.com/6694151/34527002-0c69b9c0-f072-11e7-97e9-5c2c2ca25764.jpg)

## Packet

`docker ps` - It does not run at all

![screen shot 2018-01-03 at 10 39 52 am](https://user-images.githubusercontent.com/6694151/34527109-7f978896-f072-11e7-8e2d-5bb8774dfa87.jpg)

`docker service logs miner` - I see these issues in the logs

![screen shot 2018-01-03 at 10 41 45 am](https://user-images.githubusercontent.com/6694151/34527252-fd9e295c-f072-11e7-9044-968b08f38ba3.jpg)

## Scaleway

same issue as packet

## Question

Any idea about how to debbug this?
Cheers!

**Comment by alexellis** [comment]
I'd suggest you share your commands with me confidentially so I can check the the output. I know for a fact this runs on Packet and on Civo. For the atom CPU use the `atom` tag. Mining with an atom CPU isn't a great idea though :-)

**Comment by pascalandy** [comment]
Got it for Atom CPU. 

Let me continue to go deeper and try to see what's going wrong here. I'll follow up soon :)

**Comment by fvilers** [comment]
Hi, I got the same kind of errors on different environments (windows, linux, cloud) after several hours running. How can I find the cause and/or help to fix that?

**Comment by alexellis** [comment]
What exact error @fvilers? "same sort of error" means nothing to me.

I have this working on a variety of Intel hardware in the cloud and on physical machines. Sometimes a stratum server in one of the locations will time out for cryptonight or hodl so you may want to use a different location or to switch algorithm. Unless you can convince me the solution is broken it's over to you to seek support from NiceHash or whatever pool you're  using.

**Comment by fvilers** [comment]
Sorry for being vague @alexellis. Same sort of error was connectivity issue aka:
```
miner.0.mv4z0oujw41z@laptop    | [2018-01-05 13:15:41] stratum_recv_line failed
miner.0.mv4z0oujw41z@laptop    | [2018-01-05 13:15:41] ...retry after 10 seconds
```

I'm new to this (mining coin) so I could not determine if this a pool issue, or a `cpuminer` issue. I didn't mean to exasperate you like that. I was just trying to say that I had the same issue than op and that I'm open to help.

**Comment by alexellis** [comment]
Change the stratum server location - go to nicehash.com for a list of locations. Try hodl and / or cryptonight. I sometimes change from EU to USA or HK stratum servers, but ideally you should use one close to your location. Cryptonight can give that error at times but is the most profitable, Hodl should run very reliably. You're not saying which one you're using either.

**Comment by fvilers** [comment]
Indeed, I use cryptonight. I'll try to change server as advised. Thanks Alex!
