### ISSUE TITLE
(Potential) issue with cryptonight

### ISSUE THREAD

**Issue by larse514** [alexellis/mine-with-docker#5]
Hi, I am playing around with this repo and I had a quick question on whether something wasn't working. 

I mined a bit with hodl and that seemed to work fine, the nicehash link showed my production and everything.

I switched over to try CryptoNite and it no longer seems to show an Accepted or Rejected speed rate. I can see it as an Active worker on nicehash, but it just doesn't seem to be accumulating any BTC

When I look at the container logs I can see it mining fine
`[2018-01-13 20:56:44] CPU #5: 6 H, 39.31 H/s
[2018-01-13 20:56:44] CPU #6: 6 H, 35.42 H/s
[2018-01-13 20:56:44] CPU #0: 6 H, 36.84 H/s
[2018-01-13 20:56:44] CPU #4: 6 H, 36.87 H/s
[2018-01-13 20:56:44] CPU #3: 7 H, 39.66 H/s
[2018-01-13 20:56:44] CPU #7: 7 H, 39.89 H/s
[2018-01-13 20:56:44] CPU #2: 7 H, 39.26 H/s
[2018-01-13 20:56:44] CPU #1: 6 H, 36.45 H/s
`
but I notice I don't see any Accepted logs.  Anything I may be doing wrong?

Thanks in advance and let me know if you need further clarification

**Comment by alexellis** [comment]
This log shows hashes being computed successfully. You should see some lines saying "Accepted" - if you see any red lines with errors you may want to pick a different stratum server.
