### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ghost** [alexellis/mine-with-docker#6]
Just out of curiosty, why does a raspberry pi cluster not work?

**Comment by rgee0** [comment]
@AdamSWheatley its not supported by the software being used - see https://github.com/JayDDee/cpuminer-opt

**Comment by alexellis** [comment]
Thanks for commenting Richard.

That is one of the reasons, but I have rebuilt cpuminer for ARM and it's so slow that you don't get any shares and are effectively burning money. The RPis are working at full blast and not getting any payout.
