### ISSUE TITLE
Issues Running

### ISSUE THREAD

**Issue by vZeroG** [alexellis/mine-with-docker#7]
I am somewhat new to this and am seeing this status on my Ubuntu server when running:

![image](https://user-images.githubusercontent.com/30811086/35651944-22f8b9a2-06a7-11e8-8cc4-c8f161ddcead.png)

Any ideas? Nothing crazy in the logs that I can see. I did try rebuilding the image to see if that worked, hence the latest.

**Comment by vZeroG** [comment]
As a follow up, there may be other logs that I need to examine, the only one that I have reviewed so far is:

docker service logs miner

Are there others that may help figure this out?

**Comment by vZeroG** [comment]
I believe I found the issue - my CPU does not support something that the current version of cpuminer-opt requires (AES). I have manually installed and compiled the legacy version and have made progress. Closing for now, thanks!

**Comment by alexellis** [comment]
Which CPU do you have @sgalbincea ?

**Comment by vZeroG** [comment]
2x Intel Xeon CPU X5650 @ 2.67GHz (Dell PowerEdge R710)

**Comment by gabrielmocan** [comment]
@sgalbincea can you describe your solution please?
