### ISSUE TITLE
Error: This node is not a swarm manager

### ISSUE THREAD

**Issue by xeoncross** [alexellis/mine-with-docker#8]
I'm trying to run this container as the readme states, but 

```
docker service create --mode=global \
   --name miner alexellis2/cpu-opt:2018-1-2 ./cpuminer \
   -a cryptonight \
   -o stratum+tcp://cryptonight.usa.nicehash.com:3355 \
   -u 39eAUTFxjv7TZVBienbm3kNjmNGCRrAMdT.cloud2
```

However, I get the following error on ubuntu

    Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

**Comment by bjorntheart** [comment]
@Xeoncross I'm getting the same issue. Did you manage to resolve this?

**Comment by alexellis** [comment]
Just follow the message presented to you 👍 

```
docker swarm init
```

**Comment by bjorntheart** [comment]
thanks @alexellis I ended up doing that, but was a bit slow to post back here :)

**Comment by alexellis** [comment]
Glad you got it working.. I'll just go and double check the instructions on the README. Have fun

**Comment by bjorntheart** [comment]
I'm playing around with your project on a Google Cloud Platform VM. The setup was pretty seamless apart from my inexperience with Docker and not reading the Docker swarm instructions in the shell properly :P
I don't have much Docker experience to boot so it's a bit of a learning curve for me.

I'm super excited to try out your **spotminer**, which I discovered this morning.

**Comment by mosesliao** [comment]
i already initiate kubernetes on my mac. do i still need to run docker swam init?
